#!/bin/bash
# //====================================================
# //	System Request:Debian 10/Ubuntu 18.04+/20+
# //	Author:	DevilsTunnel
# //	Dscription: Xray Menu Management
# //	email: csordervpn@gmail.com
# //  telegram: https://t.me/Rizyul04
# //====================================================
# // font color configuration | Devils Tunnel AUTOSCRIPT
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
GRENN="\e[92;1m"
WC='\033[0m'
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
# Getting
#satusbot
bot_dvs=$(systemctl status devils | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
# STATUS SERVICE  BOT 
if [[ $bot_dvs == "running" ]]; then 
   status_bot="${GREEN}Online$NC${c} $NC"
else
   status_bot="${RED}Offline${NC} "
fi
#####
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear 
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e " $COLBG1        ${WH}⇱ MENU BOT PANEL & NOTIF ⇲        $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"   
echo -e "$COLOR1  ${KIRI} Status Bot ( ${status_bot}  )     ${NC}"
echo -e "$COLOR1                                            ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH}Add Bot Panel     ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH}Delete Bot Panel  ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH}Add Bot Notifikasi${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH}Delete Notifikasi ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}Stop Bot Panel    ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}Restart Bot Panel ${NC}"
echo -e "$COLOR1  $NC ${WH}[${COLOR1}00${WH}]${NC} ${COLOR1}• ${WH}Back To Menu      ${NC}"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo -e ""
read -p " Select menu :  "  opt
echo -e   ""
case $opt in
01 | 1) clear ; wget -q https://raw.githubusercontent.com/DevilsTunnels/dvs/main/menu/b-dvs.sh && chmod +x b-dvs.sh && ./b-dvs.sh ;;
02 | 2) clear ; hapus-bot ;;
03 | 3) clear ; add-bot-notif ;;
04 | 4) clear ; del-bot-notif ;;
05 | 5) clear ; stop-bot ;;
06 | 6) clear ; restart-bot ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac
