#!/bin/bash
# //====================================================
# //	System Request:Debian 10/Ubuntu 18.04+/20+
# //	Author:	DevilsTunnel
# //	Dscription: Xray Menu Management
# //	email: csordervpn@gmail.com
# //  telegram: https://t.me/Rizyul04
# //====================================================
# // font color configuration | Devils Tunnel AUTOSCRIPT
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
sldomain=`cat /etc/xray/dns`
slkey=`cat /etc/slowdns/server.pub`
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
echo -e "$COLOR1╔════════════════════════════════════════════════╗${NC}"
echo -e " $COLBG1              ${WH}⇱  Add SSH Account ⇲              ${NC}"
echo -e "$COLOR1╚════════════════════════════════════════════════╝${NC}"
echo "   Setup Limit Quota/ip for Account "
echo "    ➤  0 For Unlimited/No Limit "
echo "    ➤  1-999 For limited/Limit "
echo ""
echo "   Username : $user"
until [[ $PASSWD =~ ^[a-zA-Z0-9]+$ ]]; do
  read -p "   Password : " PASSWD
done
until [[ $masaaktif =~ ^[0-9]+$ ]]; do
  read -p "   Expired (days): " masaaktif
done
until [[ $iplimit =~ ^[0-9]+$ ]]; do
  mkdir -p /etc/dvs/limit/ssh/ip
  read -p "   Limit User (IP): " iplimit
done
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $user
expi="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n"|passwd $user &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
if [[ ${c} != "0" ]]; then
  echo "${iplimit}" >/etc/dvs/limit/ssh/ip/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${PASSWD} ${iplimit} ${exp}" >>/etc/ssh/.ssh.db

cat >/var/www/html/ssh-$user.txt <<END

---------------------
Format SSH OVPN Account
---------------------

Username         : $user
Password         : $PASSWD
Expired          : $exp
---------------------
IP               : $ipsaya
Host             : $domain
Host Slowdns     : $sldomain
Pub Key          : $slkey
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100 - 7900
---------------------
SSH UDP : $domain:1-65535@$user:$PASSWD
---------------------
OpenVPN Config : http://$domain:81/all-ovpn.zip
---------------------
Payload WSS: GET wss://$domain/ HTTP/1.1[crlf]Host: BUG[crlf]Upgrade: websocket[crlf][crlf] 
---------------------

END

TEXT="
<code>──────────────────</code>
<code>    SSH OVPN Premium Account   </code>
<code>──────────────────</code>
<code>Username        : </code> <code>$user</code>
<code>Password        : </code> <code>$PASSWD</code>
<code>Expired          : </code> <code>$exp</code>
<code>──────────────────</code>
<code>IP               : </code> <code>$ipsaya</code>
<code>Host             : </code> <code>$domain</code>
<code>Host Slowdns     : </code> <code>$sldomain</code>
<code>Pub Key          : </code> <code> $slkey</code>
<code>Port OpenSSH     : </code> <code>22</code>
<code>Port Dropbear    : </code> <code>109, 143</code>
<code>Port DNS         : </code> <code>80, 443,53</code> 
<code>Port SSH WS      : </code> <code>80</code>
<code>Port SSH SSL WS  : </code> <code>443</code>
<code>Port SSL/TLS     : </code> <code>443</code>
<code>Port OVPN WS SSL : </code> <code>443</code>
<code>Port OVPN SSL    : </code> <code>443</code>
<code>Port OVPN TCP    : </code> <code>443, 1194</code>
<code>Port OVPN UDP    : </code> <code>2200</code>
<code>OpenVPN CONFIG      : </code> https://$domain:81/all-ovpn.zip
<code>Proxy Squid      : </code> <code>3128</code>
<code>BadVPN UDP       : </code> <code>7100 - 7900</code>
<code>───────────────────</code>
<code>SSH UDP  :</code> <code>$domain:1-65535@$user:$PASSWD</code>
<code>Payload WS   : </code> <code>GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>───────────────────</code>
<code>Save Link Account      : </code> https://$domain:81/ssh-$user.txt
"

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

if [[ ! -z "${PID}" ]]; then

clear
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLBG1${WH}⇱ SSH ACCOUNT ⇲ ${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Expired On ${COLOR1}: ${WH}$exp"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$ipsaya" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host             ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplimit} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/all-ovpn.zip" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}$sldomain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}$slkey" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss:///$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC} ${WH}https://$domain:81/ssh-$user.txt"
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
else

echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLBG1${WH}⇱ SSH ACCOUNT ⇲ ${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Expired On ${COLOR1}: ${WH}$exp"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$ipsaya" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host             ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplimit} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/all-ovpn.zip" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}$sldomain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}$slkey" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss:///$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC} ${WH}https://$domain:81/ssh-$user.txt"
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
fi
echo "" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws