#!/bin/bash
# //====================================================
# //	System Request:Debian 10/Ubuntu 18.04+/20+
# //	Author:	DevilsTunnel
# //	Dscription: Xray Menu Management
# //	email: csordervpn@gmail.com
# //  telegram: https://t.me/Rizyul04
# //====================================================
# // font color configuration | Devils Tunnel AUTOSCRIPT
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
grenbo="\e[92;1m"
GRENN="\e[92;1m"
WC='\033[0m'
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"
clear
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
echo "Checking VPS"
clear
if [ ! -e /usr/local/bin/reboot_otomatis ]; then
echo '#!/bin/bash' > /usr/local/bin/reboot_otomatis 
echo 'tanggal=$(date +"%m-%d-%Y")' >> /usr/local/bin/reboot_otomatis 
echo 'waktu=$(date +"%T")' >> /usr/local/bin/reboot_otomatis 
echo 'echo "Sucsesfully Reboot On $tanggal Time $waktu." >> /root/log-reboot.txt' >> /usr/local/bin/reboot_otomatis 
echo '/sbin/shutdown -r now' >> /usr/local/bin/reboot_otomatis 
chmod +x /usr/local/bin/reboot_otomatis
fi
clear
echo -e ""
echo -e "$COLOR1╔═════════════════════════════════════════╗${NC}"
echo -e " $COLBG1       ${WH}⇱ MENU MANAGER AUTOREBOOT ⇲        ${NC}"
echo -e "$COLOR1╚═════════════════════════════════════════╝${NC}"
echo -e "$COLOR1╔═════════════════════════════════════════╗${NC}"
echo -e "$COLOR1$NC  ${WH}1.${NC} ${COLOR1}Set Auto-Reboot 1 Hour Period ${NC}"
echo -e "$COLOR1$NC  ${WH}2.${NC} ${COLOR1}Set Auto-Reboot 6 Hour Period ${NC}"
echo -e "$COLOR1$NC  ${WH}3.${NC} ${COLOR1}Set Auto-Reboot 12 Hour Period ${NC}"
echo -e "$COLOR1$NC  ${WH}4.${NC} ${COLOR1}Set Auto-Reboot 1 Day Period ${NC}"
echo -e "$COLOR1$NC  ${WH}5.${NC} ${COLOR1}Set Auto-Reboot 1 Week Period ${NC}"
echo -e "$COLOR1$NC  ${WH}6.${NC} ${COLOR1}Set Auto-Reboot 1 Month Period ${NC}"
echo -e "$COLOR1$NC  ${WH}7.${NC} ${COLOR1}Deactivate Auto-Reboot ${NC}"
echo -e "$COLOR1$NC  ${WH}8.${NC} ${COLOR1}See Reboot Log ${NC}"
echo -e "$COLOR1$NC  ${WH}9.${NC} ${COLOR1}Delete Reboot Log${NC}"
echo -e "$COLOR1$NC "
echo -e "$COLOR1$NC  ${WH}0.${NC} ${COLOR1}BACK TO EXIT MENU ${NC}"
echo -e "$COLOR1╚═════════════════════════════════════════╝${NC}"
echo
read -p " Select menu : " opt
echo -e ""
case $opt in
1 | 01)
clear
echo "59 * * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m1 Hour Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
2 | 02)
clear
echo "10 */6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m6 Hour Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
3 | 03)
clear
echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m12 Hour Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
4 | 04)
clear
echo "0 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m1 Day Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
5 | 05)
clear
echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m1 Week Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
6 | 06)
clear
echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set By \e[32m1 Month Period\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
7 | 07)
clear
rm -f /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully \e[31mDeactivated ..!\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
8 | 08)
clear
if [ ! -e /root/log-reboot.txt ]; then
	echo "No Activity Found"
  echo -e "$COLOR1══════════════════════════════════════════$NC"
	else 
	#echo ' LOG REBOOT |'
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
echo -e "$COLOR1$NC\033[42m               LOG TIME REBOOT            $NC"
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo -e "$COLOR1╔══════════════════════════════════════════╗$NC"
cat /root/log-reboot.txt
echo -e "$COLOR1╚══════════════════════════════════════════╝$NC"
echo -e "$COLOR1══════════════════════════════════════════$NC"
fi
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
9 | 09)
clear
echo "" > /root/log-reboot.txt
echo -e "Auto Reboot Log Sucsesfully \e[31mDeleted ..!\e[0m"
echo -e "$COLOR1══════════════════════════════════════════$NC"
read -n 1 -s -r -p "Press any key to back on menu"
autoreboot
;;
0 | 00)
clear
menu
;;
x)
exit
;;
*)
echo -e ""
autoreboot
;;
esac
