#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
# ==========================================
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)

clear
Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
Info="${Green_font_prefix}[ON]${Font_color_suffix}"
Error="${Red_font_prefix}[OFF]${Font_color_suffix}"
cek=$(grep -c -E "^# Autokill" /etc/cron.d/tendang)
if [[ "$cek" = "1" ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear
echo -e ""
echo -e "$COLOR1╔═════════════════════════════════════════════════╗${NC}"
echo -e " $COLBG1             ${WH}⇱ AUTO INFO LOGIN SSH ⇲             $NC"
echo -e "$COLOR1╚═════════════════════════════════════════════════╝${NC}"
echo -e "Status Autokill : $sts        "
echo -e ""
echo -e "[1]  AutoInfo After 1 Minutes"
echo -e "[2]  AutoInfo After 5 Minutes"
echo -e "[3]  AutoInfo After 10 Minutes"
echo -e "[4]  Turn Off AutoKill/MultiLogin"
echo -e "[0]  Back To MENU"
echo ""
echo -e "$COLOR1═══════════════════════════════════════════════════${NC}"
echo -e ""
read -p "Select From Options [1-4 or x] :  " AutoKill
echo -e ""
case $AutoKill in
                1)
                echo -e ""
                read -p "Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/5 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
                echo -e ""
                echo -e "     Allowed MultiLogin : $max"
                echo -e "     AutoKill Every     : 5 Minutes"      
                echo -e ""
                echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"                                                                                                                                
                exit                                                                  
                ;;
                2)
                echo -e ""
                read -p "Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/10 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
                echo -e ""
                echo -e "     Allowed MultiLogin : $max"
                echo -e "     AutoKill Every     : 10 Minutes"      
                echo -e ""
                echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"       
                exit
                ;;
                3)
                echo -e ""
                read -p "Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/15 * * * *  root /usr/bin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
                echo -e ""
                echo -e "     Allowed MultiLogin : $max"
                echo -e "     AutoKill Every     : 15 Minutes"      
                echo -e ""
                echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"       
                exit
                ;;
                4)
                clear
                echo > /etc/cron.d/tendang
                echo -e ""
                echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
                echo -e ""
                echo -e "     AutoKill MultiLogin Turned Off  "
                echo -e ""
                echo -e "$COLOR1╚═════════════════════════════════════╝${NC}" 
                exit
				;;
                0)
				menu
                ;;
                x)
                clear
                exit
                ;;
        esac
