#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
grenbo="\e[92;1m"
GRENN="\e[92;1m"
WC='\033[0m'
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
IP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
DATEVPS=$(date +"%Y-%m-%d")
clear
echo "Mohon Menunggu , Proses Backup sedang berlangsung !!"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
    mkdir -p /root/backup
    cp -r /etc/xray/config.json backup/ >/dev/null 2>&1
    cp -r /etc/xray/*.log backup/ >/dev/null 2>&1
    cp /etc/passwd backup/
    cp /etc/group backup/
    cp /etc/shadow backup/
    cp /etc/gshadow backup/
    cp -r /var/www/html backup/html
    cp -r /etc/limit/vmess/ backup/vmess
    cp -r /etc/limit/vless/ backup/vless
    cp -r /etc/limit/trojan/ backup/trojan
    cp -r /etc/limit/shadowsocks/ backup/shadowsocks
	cp -r /etc/dvs/ backup/limit
    cp -r /etc/ssh/.ssh.db backup/ssh.db
    cp -r /etc/vmess/.vmess.db backup/vmess.db
    cp -r /etc/vless/.vless.db backup/vless.db
    cp -r /etc/trojan/.trojan.db backup/trojan.db
    cp -r /etc/shadowsocks/.shadowsocks.db backup/shadowsocks.db
    cp -r /etc/ssh/ backup/database
    cp -r /etc/vmess/ backup/database
    cp -r /etc/vless/ backup/database
    cp -r /etc/trojan/ backup/database
    cp -r /etc/ssh/ backup/database
    cp -r /etc/shadowsocks/ backup/database
    cp -r /etc/slowdns/server.pub backup/server.pub
    cp -r /etc/slowdns/server.key backup/server.key
zip -r DT-$IP-$MEK.zip backup
rclone copy DT-$IP-$MEK.zip dr:backup/
url=$(rclone link dr:backup/DT-$IP-$MEK.zip)
id=(`echo $url | grep '^https' | cut -d'=' -f2`)
LINKBACKUP="https://drive.google.com/u/4/uc?id=${id}&export=download"
echo $LINKBACKUP >/etc/xray/link
clear
sleep 2
echo -e " ${COLOR1}╔═════════════════════════════════════════╗${p}"
echo -e "    $COLBG1     ${WH}⇱ SUCCESSFULL BACKUP YOUR VPS ⇲     $NC"
echo -e " ${COLOR1}╚═════════════════════════════════════════╝${p}"
echo -e " ${COLOR1}╔═════════════════════════════════════════╗${p}"
echo -e " ${b} Your VPS IP${p} : ${g}$IP${p}"
echo -e " ${b} DOMAIN${p}      : ${g}$HOST${p}"
echo -e " ${b} DATE${p}        : ${g}$DATEVPS${p}"
echo -e " ${b} ISP${p}         : ${g}$ISPVPS${p}"
echo -e " ${b} LOCATION${p}    : ${g}$CITY${p}"
echo -e " ${b} ID BACKUP${p}   : ${g}$id${p}"
echo -e " ${COLOR1}╚═════════════════════════════════════════╝${p}"
echo -e "     Please Save The Following Data"
rm -r backup && rm DT-$IP-$MEK.zip
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>   ⚠️BACKUP NOTIF⚠️</b>
<b>     Detail Backup VPS</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<b>IP VPS  :</b> <code>${IP} </code>
<b>DOMAIN :</b> <code>${domain}</code>
<b>Tanggal : $DATEVPS</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<b>ID Backup       :</b> $id
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Silahkan copy Link dan restore di VPS baru</code>
<code>BY : @rizyul04</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
clear