#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
grenbo="\e[92;1m"
GRENN="\e[92;1m"
WC='\033[0m'
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear 
echo -e "$COLOR1╔════════════════════════════════════════════════════╗${NC}"
echo -e " $COLBG1                ${WH}⇱ BANDWITH MONITOR ⇲                 ${NC}"
echo -e "$COLOR1╚════════════════════════════════════════════════════╝${NC}"
echo -e "$COLOR1╔════════════════════════════════════════════════════╗${NC}"
echo -e "$COLOR1║ [$WH•1\e[0m] Lihat Total Bandwith Tersisa            ${NC}"
echo -e "$COLOR1║ [$WH•2\e[0m] Tabel Penggunaan Setiap 5 Menit         ${NC}"
echo -e "$COLOR1║ [$WH•3\e[0m] Tabel Penggunaan Setiap Jam             ${NC}"
echo -e "$COLOR1║ [$WH•4\e[0m] Tabel Penggunaan Setiap Hari            ${NC}"
echo -e "$COLOR1║ [$WH•5\e[0m] Tabel Penggunaan Setiap Bulan           ${NC}"
echo -e "$COLOR1║ [$WH•6\e[0m] Tabel Penggunaan Setiap Tahun           ${NC}"
echo -e "$COLOR1║ [$WH•7\e[0m] Tabel Penggunaan Tertinggi              ${NC}"
echo -e "$COLOR1║ [$WH•8\e[0m] Statistik Penggunaan Setiap Jam         ${NC}"
echo -e "$COLOR1║ [$WH•9\e[0m] Lihat Penggunaan Aktif Saat Ini         ${NC}"
echo -e "$COLOR1║ [$WH10\e[0m] Lihat Trafik Penggunaan Aktif Saat Ini [5s]${NC}"
echo -e "$COLOR1║                                                      ${NC}" 
echo -e "$COLOR1║ [$RED•0\e[0m] \e[31mBACK TO MENU\033[0m               ${NC}"
echo -e "$COLOR1║ [$RED•x\e[0m] Keluar                                  ${NC}"
echo -e "$COLOR1╚════════════════════════════════════════════════════╝${NC}" 
echo -e ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1          ${WH}⇱ TOTAL BANDWITH SERVER TERSISA ⇲           ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

2)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1          ${WH}⇱ TOTAL BANDWITH SETIAP 5 MENIT ⇲          ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -5

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

3)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1            ${WH}⇱ TOTAL BANDWITH SETIAP JAM ⇲            ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -h

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

4)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1            ${WH}⇱ TOTAL BANDWITH SETIAP HARI ⇲           ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -d

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

5)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1            ${WH}⇱ TOTAL BANDWITH SETIAP BULAN ⇲          ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -m

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

6)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1           ${WH}⇱ TOTAL BANDWITH SETIAP TAHUN ⇲           ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -y

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

7)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1             ${WH}⇱ TOTAL BANDWITH TERTINGGI ⇲            ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -t

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

8)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1          ${WH}⇱ STATISTIK TERPAKAI SETIAP JAM ⇲          ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -hg

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

9)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1              ${WH}⇱ LIVE BANDWITH SAAT INI ⇲             ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e   " Press [ Ctrl+C ] • To-Exit"
echo -e ""

vnstat -l

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

10)
clear 
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e "$COLBG1         ${WH}⇱ LIVE TRAFIK PENGGUNAAN BANDWITH ⇲         ${NC}"
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""

vnstat -tr

echo -e ""
echo -e "$COLOR1═════════════════════════════════════════════════════\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

0)
sleep 1
menu
;;
x)
exit
;;
*)
echo -e ""
echo -e "wrong bro"
sleep 1
bw
;;
esac
