#!/bin/bash
# Color
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1         ${WH}⇱ Delete Shadowsocks Account ⇲        ${NC}"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo ""
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/shadowsocks/.shadowsocks.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo ""
    echo "  No customer name available"
    echo ""
    exit 0
fi
echo "    Select the existing client you want to remove"
echo "    Press CTRL+C to return"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "     NO USERNAME EXPIRED"
echo "     ---------------------"
grep -E "^### " "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        echo ""
        until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
            read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
        done
        user=$(grep -E "^### " "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
        exp=$(grep -E "^### " "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
        sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/shadowsocks/.shadowsocks.db
        rm /etc/xray/log-create-${user}.log
        systemctl restart xray >/dev/null 2>&1
        clear
	echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo -e "$COLBG1    ${WH}shadowsocks Account Deleted Successfully     ${NC}"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo "    Client Name : $user"
    echo "    Expired On  : $exp"
	echo "    account has been permanently deleted"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
	echo ""
        exit
    fi
done