#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########

    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1            ${WH}⇱ Edit Limit ALL Vmess ⇲             $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "   You have no existing clients!"
        echo ""
        exit 0
    fi
    listmem=$(grep -s "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | nl)
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1            ${WH}⇱ Edit Limit ALL Vmess ⇲             $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo " Select the existing client you want to Edit"
		echo " Press ctrl+c To Return"
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"		
		echo "    NO  USERNAME EXPIRED"    
		echo "    ------------------------"
		echo "$listmem"
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '1' ]]; do
        echo -e " "
        read -rp "Input Username : " user
        CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

        if [[ ${CLIENT_EXISTS} == '0' ]]; then
            echo "No customer name available"
        else
            sec=3
            spinner=(⣻ ⢿ ⡿ ⣟ ⣯ ⣷)
            while [ $sec -gt 0 ]; do
                echo -ne "\e[33m ${spinner[sec]} Setting up a Premium Account $sec seconds...\r"
                sleep 1
                sec=$(($sec - 1))
            done
            clear
            echo -e "${COLOR1}INPUT DEPENDECIES ACCOUNT${NC} ${WH}$user${NC}"
			until [[ $Quota =~ ^[0-9]+$ ]]; do
            read -p "Limit User (GB): " Quota
            done
            until [[ $iplimit =~ ^[0-9]+$ ]]; do
            read -p "Limit User (IP): " iplimit
            done

            if [ ! -e /etc/vmess ]; then
                mkdir -p /etc/vmess
            fi
            if [ -z ${iplimit} ]; then
                iplimit="0"
            fi
             if [ -z ${Quota} ]; then
                Quota="0"
            fi
            c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
            d=$((${c} * 1024 * 1024 * 1024))           
            if [[ ${c} != "0" ]]; then
                echo "${iplimit}" >/etc/dvs/limit/vmess/ip/$user
				echo "${d}" > /etc/limit/vmess/${user}
            fi
            clear
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
	echo -e "$COLBG1        ${WH}Vmess Account Successfully Edited        $NC"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    echo " Client Name     : $user"
    echo " Limit IP Ready  : $iplimit IP"
	echo " Limit BW Ready  : $Quota GB"
    echo ""
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
            echo ""
            exit
        fi
    done
