#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear

function list-trojan(){
clear
domain=$(cat /etc/xray/domain)

NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo -e "$COLBG1            ${WH}⇱ CHECK TROJAN CONFIG ⇲            ${NC}"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo ""
		echo "    You have no existing clients!"
		echo ""
		echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
                read -n 1 -s -r -p "Press any key to back on menu"
        menu-trojan
	fi

    	echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo -e "$COLBG1            ${WH}⇱ CHECK TROJAN CONFIG ⇲            ${NC}"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo "    Select the existing client to view the config"
        echo "    Press CTRL+C to return"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo "     No  User   Expired"
        grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
		echo -e "$COLOR1═══════════════════════════════════════════════${NC}"			
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
clear

user=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
uuid=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`

trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${bug}:80?path=%2Ftrojan-ws&security=auto&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END

---------------------
Format Trojan GO/WS
---------------------
- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

---------------------
Format Trojan gRPC
---------------------
- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc
END

clear
clear
clear
clear
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLBG1${WH}⇱ XRAY TROJAN ⇲${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Remarks        ${COLOR1}: ${WH}${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Host           ${COLOR1}: ${WH}${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port TLS       ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port none TLS  ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port gRPC      ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Key            ${COLOR1}: ${WH}${uuid}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Path WS        ${COLOR1}: ${WH}/trojan-ws" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}ServiceName    ${COLOR1}: ${WH}trojan-grpc" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Link TLS ${COLOR1}: ${WH}${trojanlink1}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Link None TLS ${COLOR1}: ${WH}${trojanlink2}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Link gRPC ${COLOR1}: ${WH}${trojanlink3}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Format OpenClash ${COLOR1}: ${WH}https://${domain}:81/trojan-$user.txt"
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Expired On ${COLOR1}: ${WH}$exp"            | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1───────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo "" | tee -a /etc/xray/log-create-${user}.log
read -n 1 -s -r -p "Press any key to back on menu"
menu-trojan
}
clear
function editquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/.trojan.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Edit Limit Trojan ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        echo "You have no existing clients!"
        echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-trojan
       fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Edit Limit Trojan ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        grep -E "^### " "/etc/trojan/.trojan.db" | cut -d ' ' -f 2 | column -t | sort | uniq
        echo ""
        red "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
        if [ -z $user ]; then
        m-trojan
        else
        read -p "Limit (Quota): " Quota
		echo -e "$[$Quota * 1024 * 1024 * 1024]" > /etc/trojan/${user}
		clear
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1       ${WH}Trojan Account Successfully Edited	     $NC"
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
		echo " Client Name  : $user"
		echo " Quota Ready  : $Quota GB"
		echo ""
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
	fi

}

function editlimit(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/.trojan.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Edit Limit Trojan ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
                echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-trojan
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Edit Limit Trojan ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
        grep -E "^### " "/etc/trojan/.trojan.db" | cut -d ' ' -f 2 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-trojan
    else
    read -p "Limit (IP): " ips
    echo -e "${ips}" > /etc/dvs/limit/trojan/ip/${user}
    clear
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo -e "$COLBG1${WH}  Trojan Account Successfully Edited        $NC"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    echo " Client Name  : $user"
    echo " Limit IP Ready  : $ips IP"
    echo ""
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    fi
}
function resquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/trojan/.trojan.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo -e " $COLBG1            ${WH}⇱ Reset Quota Trojan ⇲              $NC"
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
                echo ""
                echo "You have no existing clients!"
                echo ""
                echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo ""
				read -n 1 -s -r -p "Press any key to back on menu"
				m-trojan
        fi

        clear
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo -e " $COLBG1            ${WH}⇱ Reset Quota Trojan ⇲             $NC"
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo ""
				grep -E "^### " "/etc/trojan/.trojan.db" | cut -d ' ' -f 2 | column -t | sort | uniq
				echo ""
				red "tap enter to go back"
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				read -rp "Input Username : " user
				if [ -z $user ]; then
				m-trojan
				else
				echo "0" > /etc/limit/trojan/${user}
				clear
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo -e "$COLBG1        ${WH}Trojan Account Successfully Reset        $NC"
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo ""
				echo " Client Name  : $user"
				echo " Successfully Resset Quota"
				echo ""
				echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
				echo ""
    fi
}
clear
echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
echo -e " $COLBG1        ${WH}⇱ TROJAN PANEL MENU ⇲        ${NC}"
echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"
echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH}Creating Trojan Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH}Creating Trojan Account MANUAL UUID${NC}" 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH}Creating Trojan Trial WS/GRPC${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLBG1            ${WH}⇱ UTILITIES ⇲            ${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH}Renew Trojan Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}Check Config Account ${NC} " 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}Check Trojan login Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH}Edit Quota Account ${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH}Edit Limit IP Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH}Reset Quota Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}10${WH}]${NC} ${COLOR1}• ${WH}Delete Trojan Account WS/GRPC${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}00${WH}]${NC} ${COLOR1}• ${WH}GO BACK${NC}"
echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"
echo -e ""
read -p "Select From Options [ 0 - 10 ] : " menu
case $menu in
1)
    addtr
    ;;
2)
    add-tru
    ;;	
3)
    trialtr
    ;;
4)
    renewtr
    ;;
5)
    list-trojan
    ;;
6)
    cektr
    ;;
7)
    editquota
    ;;
8)
    editlimit
    ;;
9)
    resquota
    ;;
10)
    deltr
    ;;
0)
    menu
    ;;	
*)
    menu
    ;;
esac