#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear
function list-vless(){
clear
domain=$(cat /etc/xray/domain)

NUMBER_OF_CLIENTS=$(grep -c -E "^#vl# " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo -e "$COLBG1             ${WH}⇱ CHECK VLESS CONFIG ⇲            ${NC}"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo ""
		echo "    You have no existing clients!"
		echo ""
		echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
                read -n 1 -s -r -p "Press any key to back on menu"
        menu-vless
	fi

	    echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo -e "$COLBG1             ${WH}⇱ CHECK VLESS CONFIG ⇲            ${NC}"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo "    Select the existing client to view the config"
        echo "    Press CTRL+C to return"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo "     No  User   Expired"
        grep -E "^#vl# " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
		echo -e "$COLOR1═══════════════════════════════════════════════${NC}"		
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
clear

user=$(grep -E "^#vl# " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
uuid=$(grep -E "^#vl# " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#vl# " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${bug}#${user}"
vlesslink2="vless://${uuid}@${bug}:80?path=/vless&security=none&encryption=none&host=${domain}&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${bug}#${user}"

cat >/var/www/html/vless-$user.txt <<-END

---------------------
Format Vless WS TLS
---------------------
- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

---------------------
Format Vless WS Non TLS
---------------------
- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

---------------------
Format Vless gRPC (SNI)
---------------------
- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

---------------------
Link Akun Vless 
---------------------
Link TLS      : 
${vlesslink1}
---------------------
Link none TLS : 
${vlesslink2}
---------------------
Link GRPC     : 
${vlesslink3}
---------------------


END

clear
clear
clear
clear
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLBG1   ${WH}⇱ XRAY VLESS ⇲${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Remarks         ${COLOR1}: ${WH}${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Domain          ${COLOR1}: ${WH}${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port TLS        ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port none TLS   ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Port gRPC       ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}id              ${COLOR1}: ${WH}${uuid}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Encryption      ${COLOR1}: ${WH}none" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Network         ${COLOR1}: ${WH}ws" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}Path            ${COLOR1}: ${WH}/vless" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${WH}ServiceName     ${COLOR1}: ${WH}vless-grpc" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${COLOR1}Link Websocket TLS      ${WH}:${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1${NC}${WH}${vlesslink1}${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${COLOR1}Link Websocket non TLS  ${WH}:${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1${NC}${WH}${vlesslink2}${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${COLOR1}Link gRPC               ${WH}:${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1${NC}${WH}${vlesslink3}${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC} ${COLOR1}Format OpenClash  ${WH}: https://${domain}:81/vless-$user.txt"
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC}${WH}Expired On ${COLOR1}: ${WH}$exp" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1────────────────────${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1 ${NC}"
read -n 1 -s -r -p "Press any key to back on menu"
m-vless
}
clear
function editquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1               ${WH}⇱ Edit Limit Vless ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
                echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-vless
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1               ${WH}⇱ Edit Limit Vless ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
        grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vless
    else
    read -p "Limit (Quota): " Quota
    echo -e "$[$Quota * 1024 * 1024 * 1024]" > /etc/vless/${user}
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1        ${WH}Vless Account Successfully Edited        $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
		echo " Client Name  : $user"
		echo " Quota Ready  : $Quota GB"
		echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""

    fi

}

function editlimit(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Edit Limit Vless ⇲               $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-vless
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1              ${WH}⇱ Edit Limit Vless ⇲               $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
        grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vless
    else
    read -p "Limit (IP): " ips
    echo -e "${ips}" > /etc/vless/limit-ip/${user}
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1        ${WH}Vless Account Successfully Edited        $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
		echo " Client Name  : $user"
		echo " Limit IP Ready  : $ips IP"
		echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
    fi
}
function resquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e " $COLBG1             ${WH}⇱ Reset Quota Vless ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-vless
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e " $COLBG1             ${WH}⇱ Reset Quota Vless ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
        grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | column -t | sort | uniq
    echo ""
    red "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vless
    else
    echo "0" > /etc/limit/vless/${user}
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1         ${WH}Vless Account Successfully Reset        $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
    echo " Client Name  : $user"
    echo " Successfully Resset Quota"
    echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
    fi
}
clear
echo -e "$COLOR1╔══════════════════════════════════════╗${NC}"
echo -e " $COLBG1          ${WH}⇱ VLESS PANEL MENU ⇲        ${NC}"
echo -e "$COLOR1╚══════════════════════════════════════╝${NC}"
echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH}Creating Vless Account WS/GRPC${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH}Creating Vless Account WS/GRPC MANUAL UUID${NC}" 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH}Creating Vless Trial WS/GRPC${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLBG1             ${WH}⇱ UTILITIES ⇲           ${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH}Renew Vless Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}Check Config Account ${NC} " 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}Check Vless login Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH}Edit Quota Account ${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH}Edit Limit IP Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH}Reset Quota Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}10${WH}]${NC} ${COLOR1}• ${WH}Delete Vless Account WS/GRPC${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}00${WH}]${NC} ${COLOR1}• ${WH}GO BACK${NC}"
echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"
echo -e ""
read -p "Select From Options [ 0 - 10 ] : " menu
case $menu in
1)
    addvless
    ;;
2)
    add-vls
    ;;	
3)
    trialvless
    ;;
4)
    renewvless
    ;;
5)
    list-vless
    ;;
6)
    cektr
    ;;
7)
    editquota
    ;;
8)
    editlimit
    ;;
9)
    resquota
    ;;
10)
    deltr
    ;;
0)
    menu
    ;;	
*)
    menu
    ;;
esac