#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear
function list-vmess(){
clear
	    echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
        echo -e "$COLBG1            ${WH}⇱ CHECK VMESS CONFIG ⇲             ${NC}"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "   You have no existing clients!"
        echo ""
        exit 0
    fi
    listmem=$(grep -s "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | column -t | nl)
    clear
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1            ${WH}⇱ CHECK VMESS CONFIG ⇲             ${NC}"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "    Select the existing client you want to remove"
echo "    Press CTRL+C to return"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "     NO USERNAME EXPIRED"
echo "     ------------------------"
    echo "$listmem"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '1' ]]; do
        echo -e " "
        read -rp "Input Username : " user
        CLIENT_EXISTS=$(grep -w $user /etc/vmess/.vmess.db | wc -l)

        if [[ ${CLIENT_EXISTS} == '0' ]]; then
            echo "No customer name available"
        else
            clear
            cat /etc/xray/log-create-${user}.log
            exit
        fi
    done
}
clear
mem-ws() {
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1             ${WH}⇱ Member Vmess Account ⇲            $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "   You have no existing clients!"
        echo ""
        exit 0
    fi
    listmem=$(grep -s "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | column -t | nl)
    clear
echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
echo -e "$COLBG1             ${WH}⇱ Member Vmess Account ⇲            $NC"
echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
echo "    Select the existing client you want to remove"
echo "    Press CTRL+C to return"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "     NO USERNAME EXPIRED"
echo "     ------------------------"
    echo "$listmem"
    exit

}
clear
function editquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1               ${WH}⇱ Edit Limit Vmess ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
                echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-vmess
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1               ${WH}⇱ Edit Limit Vmess ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        grep -E "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 5 | column -t | sort | uniq
        echo ""
        read "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vmess
    else
    read -p "Limit (Quota): " Quota
    echo -e "$[$Quota * 1024 * 1024 * 1024]" > /etc/vmess/${user}
    clear
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
	echo -e "$COLBG1       ${WH}Vmess Account Successfully Edited         $NC"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    echo " Client Name  : $user"
    echo " Quota Ready  : $Quota GB"
    echo ""
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""

    fi

}

function resquota(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e " $COLBG1             ${WH}⇱ Reset Quota Vmess ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
                echo ""
                echo "You have no existing clients!"
                echo ""
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        m-vmess
        fi

        clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e " $COLBG1            ${WH}⇱ Reset Quota Vmess ⇲               $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo ""
        grep -E "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | nl -s ') '
        echo ""
        red "tap enter to go back"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vmess
    else
    echo "0" > /etc/limit/vmess/${user}
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo -e "$COLBG1         ${WH}Vmess Account Successfully Reset        $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
		echo " Client Name  : $user"
		echo " Successfully Resset Quota"
		echo ""
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"   
		echo ""
    fi
}
clear
log-ws() {
    clear
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e "$COLBG1              ${WH}⇱ Log Vmess Account ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "   You have no existing clients!"
        echo ""
        exit 0
    fi
    listmem=$(grep -s "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | column -t | nl)
    clear
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1              ${WH}⇱ Log Vmess Account ⇲              $NC"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "    Select the existing client you want to remove"
echo "    Press CTRL+C to return"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "     NO USERNAME EXPIRED"
echo "     ------------------------"
echo "$listmem"
        echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '1' ]]; do
        echo -e " "
        read -rp "Input Username : " user
        CLIENT_EXISTS=$(grep -w $user /etc/vmess/.vmess.db | wc -l)

        if [[ ${CLIENT_EXISTS} == '0' ]]; then
            echo "No customer name available"
        else
            clear
            cat /var/log/xray/access.log | grep $user
            exit
        fi
    done
}

function login-vmess(){
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1            ${WH}⇱ SETTING MULTI LOGIN ⇲            $NC"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "  PLEASE WRITE THE AMOUNT OF TIME FOR MULTI LOGIN USERS   ${NC}"
echo -e "  THERE WILL BE A NOTIFICATION EVERY FEW MINUTES AS YOU WANT. ${NC}"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
read -rp " If you want notifications every 3 minutes then you write 3, etc: " -e notif2
echo "# Autokill" >/etc/cron.d/xraylimit
echo "SHELL=/bin/sh" >>/etc/cron.d/xraylimit
echo "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" >>/etc/cron.d/xraylimit
echo "*/$notif2 * * * *  root /usr/bin/xraylimit" >>/etc/cron.d/xraylimit
service cron restart >/dev/null 2>&1
service cron reload >/dev/null 2>&1
clear
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1            ${WH}⇱ SETTING MULTI LOGIN ⇲            $NC"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "  PLEASE WRITE THE NUMBER OF NOTIFICATIONS FOR LOCK   ${NC}"
echo -e "  MULTI LOGIN USER ACCOUNTS. ${NC}"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
read -rp "   If you want 3 new notifications to be locked, write 3, etc: " -e notif
cd /etc/vmess
echo "$notif" > notif
clear
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "$COLBG1            ${WH}⇱ SETTING MULTI LOGIN ⇲            $NC"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo -e "  LOCK NOTIFICATION SUCCESSFULLY EDITED TO $notif   ${NC}"
echo -e "  TIME THE NOTIFICATION WAS SUCCESSFULLY EDITED TO $notif2 MENIT. ${NC}"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
read -n 1 -s -r -p "Press any key to back on menu"
m-vmess
}
function res-user(){
clear
cd
if [ ! -e /etc/vmess/akundelete ]; then
  echo "" > /etc/vmess/akundelete
fi
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/akundelete")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
	    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
        echo -e " $COLBG1             ${WH}⇱ Restore Vmess Account ⇲              $NC"
        echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		echo ""
		echo "You have no existing user Expired!"
		echo ""
		echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
		read -n 1 -s -r -p "Press any key to back on menu"
        m-vmess
	fi

	clear
echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
echo -e " $COLBG1             ${WH}⇱ Restore Vmess Account ⇲              $NC"
echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
echo "    Select the existing client you want to remove"
echo "    Press CTRL+C to return"
echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
echo "     NO USERNAME EXPIRED"
echo "     ------------------------"
	grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 2-3 | nl -s ') '
	until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
		if [[ ${CLIENT_NUMBER} == '1' ]]; then
			read -rp "Select one client [1]: " CLIENT_NUMBER
		else
			read -rp "Select one client [1-${NUMBER_OF_CLIENTS}] to Unlock: " CLIENT_NUMBER
			if [[ ${CLIENT_NUMBER} == '0' ]]; then 
	m-vmess
	fi
	if [[ ${CLIENT_NUMBER} == 'clear' ]]; then
	rm /etc/vmess/akundelete
	m-vmess
	fi
	fi
	done
	until [[ $masaaktif =~ ^[0-9]+$ ]]; do
read -p "Expired (days): " masaaktif
done
until [[ $iplim =~ ^[0-9]+$ ]]; do
read -p "Limit User (IP): " iplim
done
user=$(grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
uuid=$(grep -E "^### " "/etc/vmess/akundelete" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
sed -i '/#vmess$/a\#vm '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\#vmg '"$user $exp $uuid"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
echo "${iplim}" >/etc/vmess/${user}IP
sed -i "/### $user $exp $uuid/d" /etc/vmess/akundelete
systemctl restart xray
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  XRAY VMESS RESTORE</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<b>DOMAIN   :</b> <code>${domain} </code>
<b>ISP      :</b> <code>$ISP $CITY </code>
<b>USERNAME :</b> <code>$user </code>
<b>IP LIMIT  :</b> <code>$iplim IP </code>
<b>EXPIRED  :</b> <code>$exp </code>
<code>◇━━━━━━━━━━━━━━◇</code>
<i>Succes Restore This Akun...</i>
"

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo " Vmess Account Restore Successfully"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo " DOMAIN : $domain"
    echo " ISP  : $ISP $CITY"
    echo " USERNAME : $user"
    echo " IP LIMIT : $iplim IP"
    echo " EXPIRED  : $exp"
    echo " Succes to Restore"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vmess
    }
function del-res(){
rm /etc/vmess/akundelete
echo -e "Succes Delete Log Restore/Delete Akun"
m-vmess
}
clear
echo -e "$COLOR1╔══════════════════════════════════════╗${NC}"
echo -e " $COLBG1         ${WH}⇱ VMESS PANEL MENU ⇲         ${NC}"
echo -e "$COLOR1╚══════════════════════════════════════╝${NC}"
echo -e "$COLOR1╔═════════════════════════════════════╗${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH}Create Vmess Account ${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH}Create Vmess Account MANUAL UUID${NC}" 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH}Create Vmess Trial ${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLBG1            ${WH}⇱ UTILITIES ⇲            ${NC}"
echo -e " $COLOR1═════════════════════════════════════${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH}Renew Vmess Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}Check Config Account ${NC} " 
echo -e " $COLOR1 $NC ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}Check Vmess login Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH}Member Vmess Account ${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH}Edit Quota Account ${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH}Edit Limit IP Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}10${WH}]${NC} ${COLOR1}• ${WH}Edit Limit ALL Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}11${WH}]${NC} ${COLOR1}• ${WH}Reset Quota Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}12${WH}]${NC} ${COLOR1}• ${WH}Log Vmess Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}13${WH}]${NC} ${COLOR1}• ${WH}Delete Vmess Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}14${WH}]${NC} ${COLOR1}• ${WH}Setting Time And Lock Login${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}15${WH}]${NC} ${COLOR1}• ${WH}Restore Vmess Account${NC}"
echo -e " $COLOR1 $NC ${WH}[${COLOR1}00${WH}]${NC} ${COLOR1}• ${WH}GO BACK${NC}"
echo -e "$COLOR1╚═════════════════════════════════════╝${NC}"
echo -e ""
read -p "Select From Options [ 0 - 13 ] : " menu
case $menu in
1)
    addws
    ;;
2)
    add-vms
    ;;	
3)
    trialws
    ;;
4)
    renewws
    ;;
5)
    list-vmess
    ;;
6)
    cekws
    ;;
7)
    mem-ws
    ;;	
8)
    resbwvms
    ;;
9)
    limvms
    ;;
10)
    limvmsall
    ;;	
11)
    resquota
    ;;
12)
    log-ws
    ;;
13)
    delws
    ;;	
14)
    login-vmess
    ;;
15)
    res-user
    ;;	    	    
0)
    menu
    ;;	
*)
    menu
    ;;
esac