#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear

TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=$(cat /etc/xray/domain)
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		clear
 	echo -e "$COLOR1══════════════════════════════════════════════${NC}"
    echo -e "$COLBG1               ${WH}⇱ Renew Vmess ⇲                 ${NC}"
  	echo -e "$COLOR1══════════════════════════════════════════════${NC}"
	echo ""
	echo "      You have no existing clients!"
	echo ""
	echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    menu-vmess
	fi
	listmem=$(grep -s "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | column -t | nl)
    clear
 	echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    echo -e "$COLBG1               ${WH}⇱ Renew Vmess ⇲                 ${NC}"
  	echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
	echo "    Select the existing client you want to renew"
	echo "    Press CTRL+C to return"
	echo -e "$COLOR1═══════════════════════════════════════════════${NC}"
    echo "    NO  USERNAME     EXPIRED"    
    echo "    ------------------------"
    echo "$listmem"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '1' ]]; do
        echo -e " "
        read -rp "Input Username : " user
        CLIENT_EXISTS=$(grep -w $user /etc/vmess/.vmess.db | wc -l)

        if [[ ${CLIENT_EXISTS} == '0' ]]; then
            echo "No customer name available"
        else
            sec=3
            spinner=(⣻ ⢿ ⡿ ⣟ ⣯ ⣷)
            while [ $sec -gt 0 ]; do
                echo -ne "\e[33m ${spinner[sec]} Setting up a Premium Account $sec seconds...\r"
                sleep 1
                sec=$(($sec - 1))
            done
            clear
            echo -e "${COLOR1}INPUT DEPENDECIES ACCOUNT${NC} ${WH}$user${NC}"
read -p "Expired (days): " masaaktif
read -p "Limit Quota (GB): " Quota
read -p "Limit User (IP): " iplimitit
exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
exp3=$(($exp2 + $masaaktif))
exp4=$(date -d "$exp3 days" +"%Y-%m-%d")
sed -i "/### $user/c\### $user $exp4" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
echo "### ${user} ${exp4}" >>/etc/vmess/.vmess.db
sed -i "s/${exp}/${exp4}/g" /etc/vmess/$user.log
logq=$(grep -o 'User Quota\s*:\s*[^ ]*' /etc/vmess/${user}.log | sed 's/User Quota\s*:\s*//' )
logip=$(grep -o 'Limit Adress\s*:\s*[^ ]*' /etc/vmess/$(user).log | sed 's/Limit Adress\s*:\s*//')
sed -i "s/${exp}/${exp4}/g" /var/www/html/vmess-$user.txt
sed -i "s/${logq}/${Quota}/g" /etc/vmess/$user.log
sed -i "s/${logip}/${iplimit}/g" /etc/vmess/$user.log
sed -i "s/${logq}/${Quota}/g" /var/www/html/vmess-$user.txt
sed -i "s/${logip}/${iplimit}/g" /var/www/html/vmess-$user.txt
rm /etc/vmess/cache/${user} >/dev/null 2>&1
rm /etc/vmess/${user} >/dev/null 2>&1
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplimit}" >/etc/limit/vmess/${user}
fi
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
systemctl reload xray >/dev/null 2>&1
clear
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>   XRAY VMESS RENEW</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<b>DOMAIN   :</b> <code>${domain} </code>
<b>USERNAME :</b> <code>$user </code>
<b>EXPIRED  :</b> <code>$exp4 </code>
<code>◇━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

systemctl restart xray > /dev/null 2>&1
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo -e "$COLBG1      ${WH}VMESS Account Was Successfully Renewed     ${NC}"
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
    echo ""
    echo "    Client Name : $user"
    echo "    Expired On  : $exp4"
    echo ""
    echo -e "$COLOR1═════════════════════════════════════════════════${NC}"
            echo ""
            exit
        fi
    done