#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Rizki Pratama
# (C) Copyright 2023-2024 By Devils Tunnels
# =========================================
#!/bin/bash
###########- COLOR CODE -##############
colornow=$(cat /etc/dvs/theme/color.conf)
NC="\e[0m"
p="\e[0m"
r="\033[0;31m"
y="\033[33m"
gb="\e[92;1m"
RED="\033[0;31m"
COLOR1="$(cat /etc/dvs/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/dvs/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
###########- END COLOR CODE -##########
clear
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
###### IZIN SC 
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/DevilsTunnels/permission/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
echo -e "${r} ╔═════════════════════════════════════════════════╗${p}"
echo -e "${r}═║                ${b}PERMISSION DENIED ${p}               ${r}║═${p}"
echo -e "${r}═║${y}┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┌─┐┬─┐┌─┐┌┬┐┬┬ ┬┌┬┐${p}${r}║═${p}"
echo -e "${r}═║${y}├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   ├─┘├┬┘├┤ │││││ ││││${p}${r}║═${p}"
echo -e "${r}═║${y}┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴  ┴└─└─┘┴ ┴┴└─┘┴ ┴${p}${r}║═${p}"
echo -e "${r}═║${gb}  POWERRED DEVILSTUNNEL | TELEGRAM: @Rizyul04    ${p}${r}║═${p}"
echo -e "${r} ╚═════════════════════════════════════════════════╝${p}"
echo -e "                 ${y}INFORMASI LISENSI${p}"                 
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 IP ${r}$ipsaya${p}"
echo -e "                 ${y}PERIZINAN DITOLAK${p}"
echo -e "    ${y} SCRIPT TIDAK BISA DI GUNAKAN DI VPS ANDA${p}"
echo -e "    ${y} SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
echo -e "                 ${gb}KONTAK REGISTRASI${p}"
echo -e "   ${gb}|Telegram: @Rizyul04   | WhatsApp: 085163567549|${p}"
echo -e "${r}═════════════════════════════════════════════════════${p}"
    exit
  fi
}
checking_sc
clear
red() { echo -e "\033[32;1m${*}\${p}"; }
IP=$(curl -sS ifconfig.me)
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
TIMES="10"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
echo -e "${COLOR1}╔══════════════════════════════════════════╗${NC}"
echo -e " ${COLBG1}       ${WH}⇱  Add SSH OpenVPN Account ⇲       ${NC}"
echo -e "${COLOR1}╚══════════════════════════════════════════╝${NC}"
user=Trial-SSH`</dev/urandom tr -dc 0-9 | head -c3`
CLIENT_EXISTS=$(grep -w $user /etc/ssh/.ssh.db | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
exit
clear
echo -e "${COLOR1}╔══════════════════════════════════════════╗${NC}"
echo ""
echo "       A client name was already created"
echo ""
echo -e "${COLOR1}╚══════════════════════════════════════════╝${NC}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
ssh
fi
echo -e "${COLOR1}╔══════════════════════════════════════════╗${NC}"
echo -e ""
echo -e "      ${gb}[1]•${b} Triall 15 Minutes"
echo -e "      ${gb}[2]•${b} Triall 30 Minutes"
echo -e "      ${gb}[3]•${b} Triall 1 Jam/Hours"
echo -e "      ${gb}[0]•${b} Back To Menu SSH"
echo -e ""
echo -e "${COLOR1}╚══════════════════════════════════════════╝${NC}"
echo -e ""
read -p "  Select From Options [ 1 - 3 or 0 ] : " OPT_MENU
echo -e ""
case $OPT_MENU in
1)
jamm="15 minutes"
;;
2)
jamm="30 minutes"
;;
3)
jamm="1 hours"
;;
0)
menu-ssh
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
menu
;;
esac
PASSWD=PW-`</dev/urandom tr -dc 0-9 | head -c4`
EXPIRED=1
expr=$(date -d "$EXPIRED days" +"%Y-%m-%d")
useradd -e `date -d "$EXPIRED days" +"%Y-%m-%d"` -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD
$PASSWD
"|passwd $user &> /dev/null
echo "${iplim}" >/etc/ssh/${user}
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${expr} {$PASSWD}" >>/etc/ssh/.ssh.db
cat > /var/www/html/ssh-$user.txt <<-END

---------------------
Format SSH OVPN Account
---------------------

Username         : $user
Password         : $PASSWD
Expired          : $jamm
---------------------
IP               : $ipsaya
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100 - 7900
---------------------
SSH UDP : $domain:1-65535@$user:$PASSWD
---------------------
OpenVPN Config : http://$domain:81/all-ovpn.zip
---------------------
Payload WSS: GET wss://$domain/ HTTP/1.1[crlf]Host: BUG[crlf]Upgrade: websocket[crlf][crlf] 
---------------------

END

TEXT="
<code>──────────────────</code>
<code>    SSH OVPN Premium Account   </code>
<code>──────────────────</code>
<code>Username        : </code> <code>$user</code>
<code>Password        : </code> <code>$PASSWD</code>
<code>Expired          : </code> <code>$jamm</code>
<code>──────────────────</code>
<code>IP               : </code> <code>$ipsaya</code>
<code>Host             : </code> <code>$domain</code>
<code>Host Slowdns     : </code> <code>${NS}</code>
<code>Pub Key          : </code> <code>${PUB}</code>
<code>Port OpenSSH     : </code> <code>22</code>
<code>Port Dropbear    : </code> <code>109, 143</code>
<code>Port DNS         : </code> <code>80, 443,53</code> 
<code>Port SSH WS      : </code> <code>80</code>
<code>Port SSH SSL WS  : </code> <code>443</code>
<code>Port SSL/TLS     : </code> <code>443</code>
<code>Port OVPN WS SSL : </code> <code>443</code>
<code>Port OVPN SSL    : </code> <code>443</code>
<code>Port OVPN TCP    : </code> <code>443, 1194</code>
<code>Port OVPN UDP    : </code> <code>220</code>
<code>OpenVPN CONFIG   : </code> https://$domain:81/all-ovpn.zip
<code>Proxy Squid      : </code> <code>3128</code>
<code>BadVPN UDP       : </code> <code>7100 - 7900</code>
<code>───────────────────</code>
<code>SSH UDP  :</code> <code>$domain:1-65535@$user:$PASSWD</code>
<code>Payload WS   : </code> <code>GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>───────────────────</code>
<code>Save Link Account      : </code> https://$domain:81/ssh-$user.txt
<code>───────────────────</code>
<code> @rizyulvpn                       </code>
<code>───────────────────</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

if [[ ! -z "${PID}" ]]; then

clear
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLBG1${WH}⇱ SSH ACCOUNT ⇲${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Expired On ${COLOR1}: ${WH}$jamm"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$ipsaya" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host             ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplim} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/all-ovpn.zip" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}${NS}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}${PUB}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss:///$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC} ${WH}https://$domain:81/ssh-$user.txt"
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
else

echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLBG1${WH}⇱ SSH ACCOUNT ⇲${NC}"  | tee -a /etc/xray/log-create-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Username   ${COLOR1}: ${WH}$user"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Password   ${COLOR1}: ${WH}$PASSWD" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Expired On ${COLOR1}: ${WH}$jamm"  | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}IP               ${COLOR1}: ${WH}$ipsaya" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Host             ${COLOR1}: ${WH}$domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Limit IP         ${COLOR1}: ${WH}${iplim} Login" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenSSH          ${COLOR1}: ${WH}22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Dropbear         ${COLOR1}: ${WH}109, 143" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH UDP     ${COLOR1}: ${WH}1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS      ${COLOR1}: ${WH}80" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH WS/SSL  ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port SSH SSL/TLS ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn TCP    ${COLOR1}: ${WH}443,1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn UDP    ${COLOR1}: ${WH}2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}Port Ovpn SSL    ${COLOR1}: ${WH}443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}OpenVPN Config   ${COLOR1}: ${WH}https://$domain:81/all-ovpn.zip" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}UDPGW            ${COLOR1}: ${WH}7100-7900" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PORT SLWDNS      ${COLOR1}: ${WH}80,22,53" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}NAMESERVER       ${COLOR1}: ${WH}${NS}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}PUB KEY          ${COLOR1}: ${WH}${PUB}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WSS :                                      ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET wss:///$domain/ [protocol][crlf]Host: bug.mu[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Payload WS :                  ${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${WH}GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "${COLOR1}Save Link Account:${NC} ${WH}https://$domain:81/ssh-$user.txt"
echo -e "$COLOR1─────────────────${NC}" | tee -a /etc/xray/log-createssh-${user}.log
fi
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws